# Generated by Django 5.0.6 on 2024-07-01 17:51

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(max_length=255)),
                ('key_schema', django_jsonform.models.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='AnnotationDelegateService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('retry_delay', models.PositiveIntegerField(default=5)),
                ('timeout', models.PositiveIntegerField(default=15)),
                ('annotation_keys', models.ManyToManyField(related_name='services', to='svc_app.annotationkey')),
                ('depends_on_keys', models.ManyToManyField(blank=True, related_name='dependent_services', to='svc_app.annotationkey')),
            ],
        ),
    ]
